name: Manual Nightly Build pytorch1.6 cuda9.2

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test pytorch1.7 cuda9.2 build"
  workflow_run:
    workflows: ["Trigger Nightly Builds"]
    types:
      - completed
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
        ginjinn-distribution: [ginjinn-gpu-pt16_cu92_linux]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      NIGHTLY: true
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, pytorch
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda install pytest conda-libmamba-solver anaconda-client pip pytest-cov
          conda install boa -c conda-forge
      - name: Build and publish GinJinn
        run: |
          conda config --set anaconda_upload yes
          conda mambabuild conda.recipe/${{ matrix.ginjinn-distribution }} --token ${{ secrets.ANACONDA_TOKEN }} --user AGOberprieler --variants "{'python': ['${{ matrix.python-version }}']}" --label nightly
      - name: Install GinJinn from Anaconda cloud
        run: conda install -c conda-forge -c pytorch -c agoberprieler/label/nightly ginjinn2 pytorch=1.6.0 cudatoolkit=9.2
      - name: Test with pytest
        run: |
          pytest --cov=./ginjinn/ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
