name: Manual Nightly Build pytorch1.6 cuda10.1 test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test pytorch1.6 cuda10.1 build"
  workflow_run:
    workflows: ["Trigger Nightly Builds"]
    types:
      - completed
jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
        ginjinn-distribution: [ginjinn-gpu-pt16_cu101_linux]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      NIGHTLY: true
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v4
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
          auto-update-conda: true
          channels: conda-forge, pytorch
      - run: mamba --version
      - run: which python3
      - name: Install dependencies
        run: |
          mamba install boa pytest anaconda-client pip pytest-cov conda-verify
      - name: Build and publish GinJinn2
        run: |
          mamba config --set anaconda_upload yes
          conda mambabuild conda.recipe/${{ matrix.ginjinn-distribution }} --token ${{ secrets.ANACONDA_TOKEN }} --user AGOberprieler --variants "{'python': ['${{ matrix.python-version }}']}" --label nightly
      - name: Install GinJinn2 from Anaconda cloud
        run: mamba install -c agoberprieler/label/nightly ginjinn2 pytorch=1.6.0 cudatoolkit=10.1
      - run: mamba list
      - name: Test with pytest
        run: |
          pytest --cov=./ginjinn/ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          
