name: Manual Build pytorch1.6 cuda10.1

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test pytorch1.6 cuda10.1 build"
  workflow_run:
    workflows: ["Trigger Builds"]
    types:
      - completed
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, pytorch
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda install pytest conda-libmamba-solver anaconda-client pip pytest-cov
          conda install boa -c conda-forge
      - name: Install GinJinn from Anaconda cloud
        run: |
          conda create -n gj
          source activate gj
          conda install -c conda-forge -c pytorch -c agoberprieler ginjinn2 pytorch=1.6.0 cudatoolkit=10.1 --experimental-solver=libmamba
